apiVersion: v1
kind: Service
metadata:
  name: leads
  namespace: realtor-apps
  labels:
    app: leads
spec:
  type: LoadBalancer
  selector:
    app: leads
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
