apiVersion: apps/v1
kind: Deployment
metadata:
  name: leads-crawler
  namespace: realtor-apps
  labels:
    app: leads-crawler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leads-crawler
  template:
    metadata:
      labels:
        app: leads-crawler
    spec:
      containers:
        - name: leads-crawler
          image: crawler_leads-crawler:latest
          ports:
            - containerPort: 7002
          envFrom:
            - secretRef:
                name: leads-crawler-env
